spring.application.name=TelegramBot
bot.name=Test_Java798_bot
bot.token=7597033590:AAFt8VtFYWiwZQEV5GV2DCC7XkVzIHvqJ7A



spring.datasource.url=jdbc:h2:mem:tg_bot;MODE=MySQL
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml


